### ISSUE TITLE
Missing notify characteristic changed feature

### ISSUE THREAD

**Issue by Arrowana** [WebBluetoothCG/web-bluetooth#378] opened 2017-09-30 12:52 UTC
I am trying to emulate what the Atmel Android native app is doing to communicate.
After writing to a characteristic the client (Android device) notify the server (Atmel MCU).
However I can't find any similar function in the Bluetooth web API.

https://developer.android.com/reference/android/bluetooth/BluetoothGattServer.html
**notifyCharacteristicChanged**
This function is called in the Android app.

I tried to write to the characteristic with writeValue, but this is not enough. The device need the notification.

**Comment by scheib** [comment] 2017-10-06 22:51
Web Bluetooth only supports acting as a Bluetooth Central & Client at this time.  A Client can read, write, and receive notifications sent by characteristics.  A Client can not send notifications.  At the Android API this is using the `BluetoothGatt` class. 

Duplicate of https://github.com/WebBluetoothCG/web-bluetooth/issues/78

**Closed by scheib** 2017-10-06 22:51 UTC
