### ISSUE TITLE
Discovery method

### ISSUE THREAD

**Issue by JosefJezek** [WebBluetoothCG/web-bluetooth#211] opened 2016-02-02 14:36 UTC
Could you add Discovery method? Like this startDiscovery and getDevices methods from Chrome...
https://developer.chrome.com/apps/bluetooth#method-startDiscovery

I would like to create Eddystone beacons scanner like this Physical Web android app...
https://play.google.com/store/apps/details?id=physical_web.org.physicalweb

**Comment by beaufortfrancois** [comment] 2016-02-02 14:55
It is already there. Learn more about this at https://developers.google.com/web/updates/2015/07/interact-with-ble-devices-on-the-web and check out samples at https://googlechrome.github.io/samples/web-bluetooth/device-info.html and more

**Comment by g-ortuno** [comment] 2016-02-02 14:59
I think he's referring to the scanning API #191

**Comment by beaufortfrancois** [comment] 2016-02-02 15:08
You're right.

**Comment by JosefJezek** [comment] 2016-02-02 15:56
@g-ortuno Yes, thank you :+1: 

We have also lib for node.js, check out this link
https://github.com/sandeepmistry/node-eddystone-beacon-scanner

**Comment by jyasskin** [comment] 2016-02-02 16:39
Yeah, it's still a duplicate of #191.

**Closed by jyasskin** 2016-02-02 16:39 UTC
