### ISSUE TITLE
API for an own GATT server / service

### ISSUE THREAD

**Issue by LukasBombach** [WebBluetoothCG/web-bluetooth#446] opened 2019-07-04 12:58 UTC
> 3. Have you found a problem with the way this API is specified or have
>    a feature request? File it here.

this.

From what I can tell the web-bluetooth API is intended to communicate with remote devices, usually(?) GATT services.

Would it be interesting to create an API to create and advertise an own GATT server and service?

My use-case for this is that I have a [bluetooth-enabled coffee machine](https://decentespresso.com/) (for real) and I would like to write an emulator for that, i.e. write a website that mimics the machine, basically to reverse engineer it.

I admit, this seems like a crazy and rare request, but maybe an own GATT server could be interesting for others as well?

**Comment by reillyeon** [comment] 2019-07-25 17:10
This is a duplicate of #78.

**Closed by reillyeon** 2019-07-25 17:10 UTC
