### ISSUE TITLE
Qr Code Print

### ISSUE THREAD

**Issue by luisvinicius167** [WebBluetoothCG/web-bluetooth#409] opened 2018-09-23 19:55 UTC
Hi folks. A couple of days, I'm trying to print a qr code, but It just not happen.  I'm copy/paste this code too, but it's not working too: https://github.com/WebBluetoothCG/demos/blob/gh-pages/bluetooth-printer/index.html

The same problem here: https://github.com/WebBluetoothCG/demos/issues/72

I'm really need that, so anyone have a solution?

**Comment by reillyeon** [comment] 2018-09-24 17:29
Closing this issue as a potential duplicate of WebBluetoothCG/demos#72. This is not the right issue tracker for reporting issues with any of the demo applications.

**Closed by reillyeon** 2018-09-24 17:29 UTC
