### ISSUE TITLE
[Feature Request] generate found devices in app UI, not popup

### ISSUE THREAD

**Issue by foureyedraven** [WebBluetoothCG/web-bluetooth#431] opened 2019-04-04 20:17 UTC
Based on what my team has said, generating the list of found BLE devices in the UI we build, without the need for the popup, is currently not possible. We would like our users to have the ability to connect to multiple BLE devices at once without having to approve each one in a pop up.

Could this be possible?

Thank you

**Comment by reillyeon** [comment] 2019-04-04 20:24
Closing this as a duplicate of #42. The list of found devices is rendered in a popup and not provided directly to the app so that it can present its own UI because the user agent needs to obtain user consent before it can give the app information about any nearby devices.

**Comment by foureyedraven** [comment] 2019-04-04 21:26
I'm not sure a feature request about allowing devs to create their own UI for users to connect to devices the same as allowing connection to multiple devices. Though, of course having multiple devices at once does follow naturally.

**Comment by reillyeon** [comment] 2019-04-04 22:07
The security and privacy model for this API requires that apps _not_ be allowed to create their own UI for users to connect to devices because that would leak private information before the user has given consent. The motivation for this request seemed to be so that multiple devices could be selected simultaneously which is why I considered it a duplicate. Are there additional motivations for this request?

**Comment by foureyedraven** [comment] 2019-04-05 17:50
I guess what I'm asking is, could there be ways for users to provide that consent through the UI instead? Sounds like a definite no, though?

**Comment by foureyedraven** [comment] 2019-04-05 17:51
It sounds like what I'm asking for (getting user consent through our UI) is a definite no due to the security model, so that answers my question. Thank you!

**Comment by reillyeon** [comment] 2019-04-05 18:08
Thank you for your feedback.

**Closed by reillyeon** 2019-04-05 18:08 UTC

**Comment by g-ortuno** [comment] 2019-04-07 02:22
We do have an issue to allow users to select more than one device in the chooser: #42

**Comment by g-ortuno** [comment] 2019-04-07 02:22
Oops seems like that was mentioned already!
