### ISSUE TITLE
Read RR Value from HR Device 

### ISSUE THREAD

**Issue by sebyechelon** [WebBluetoothCG/web-bluetooth#493] opened 2020-05-04 10:55 UTC
I am reading the values of my HR device through Web Bluethooth.

This is an example of read values:

```
0x10 0x3e 0xb1 0x3 0xde
0x10 0x39 0x23 0x4 0x35
0x10 0x3d 0xcf 0x3 0xef
```
I convert these numbers into decimal numbers and I have:

```
16 62 177 3 222
16 57 35 4 53
16 61 207 3 239
```
Where:

- The second column represents the heart beats per minute (62 - 57 - 61).
- The fourth column represents the RR interval (222 - 53 - 239).

But the numbers seem wrong to me. 
If I have beats around 60 per minute, I should have a higher RR interval than the value I read.

Do I make any conversion errors? Is the RR value to be read in another way?

**Comment by reillyeon** [comment] 2020-05-04 17:06
Closing this issue as a duplicate of the StackOverflow question the reporter also asked: https://stackoverflow.com/questions/61590541/webbluetoothcg-read-rr-value-from-bluetooth-device

This is a device-specific question which is off-topic for this repository.

**Closed by reillyeon** 2020-05-04 17:06 UTC
